--CREATE SCHEMA GP;
--drop table GP.Movie
--drop table GP.Links
--drop table GP.Tags
--drop table GP.Ratings

CREATE TABLE GP.Movie
(
   MovieID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
   Title NVARCHAR(25) NOT NULL UNIQUE,
   Genre NVARCHAR(200) NOT NULL,
   UpdatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET())
);
GO

CREATE TABLE GP.Links
(
   IMDBID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
   MovieID INT NOT NULL FOREIGN KEY
		REFERENCES GP.Movie(MovieID),
   TMDBID INT NOT NULL UNIQUE
);
GO

CREATE TABLE GP.Tags
(
   UserID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
   MovieID INT NOT NULL FOREIGN KEY
		REFERENCES GP.Movie(MovieID),
   Tag NVARCHAR(25) NOT NULL,
   [TimeStamp] DATETIME2(0) NOT NULL

);
GO

CREATE TABLE GP.Ratings
(
   UserID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
   MovieID INT NOT NULL FOREIGN KEY
		REFERENCES GP.Movie(MovieID),
   Rating INT NOT NULL, 
   [TimeStamp] DATETIME2(0) NOT NULL
);
GO
