DROP TABLE IF EXISTS MOVIES 
DROP TABLE IF EXISTS DIRECTORS 
DROP TABLE IF EXISTS GENRES 
DROP TABLE IF EXISTS RATINGS 

GO
CREATE TABLE MOVIES
(
		MovieID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
		Title NVARCHAR(200) NOT NULL UNIQUE,
		DirectorID INT NOT NULL,
		AverageRating INT NOT NULL,
		GenreID INT NOT NULL,
		Overview NVARCHAR(1000) NOT NULL, 
		Release_Date DATE NOT NULL
);
GO

CREATE TABLE DIRECTORS
(
		DirectorID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY FOREIGN KEY
			REFERENCES MOVIES(DirectorID),
		LastName NVARCHAR(20) NOT NULL,
		FirstName NVARCHAR(20) NOT NULL,
		DateOfBirth DATETIME2(0) NOT NULL
);
GO

CREATE TABLE GENRES
(
		GenreID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY FOREIGN KEY
			REFERENCES MOVIES(GenreID),
		[Name] NVARCHAR(20) NOT NULL,	
);
GO

CREATE TABLE RATINGS
(
		RatingID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY FOREIGN KEY
			REFERENCES MOVIES(AverageRating),
		[Name] NVARCHAR(20) NOT NULL,
		Age NVARCHAR(20) NOT NULL,

		 UNIQUE
		 (
			[Name] ASC,
			Age ASC
		 )
);
GO