DROP SCHEMA IF EXISTS GP;
GO

CREATE SCHEMA GP;
GO

DROP TABLE IF EXISTS GP.Rating
DROP TABLE IF EXISTS GP.Genre
DROP TABLE IF EXISTS GP.Region
DROP TABLE IF EXISTS GP.Director
DROP TABLE IF EXISTS GP.Actor
DROP TABLE IF EXISTS GP.Financial
DROP TABLE IF EXISTS GP.AdditionalInfo
DROP TABLE IF EXISTS GP.Movies

CREATE TABLE GP.Movies
(
   MovieID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
   Title NVARCHAR(50) NOT NULL,
   Year INT NOT NULL,
   Runtime INT NOT NULL,
   ContentRating NVARCHAR(10) NOT NULL,
   CreateddOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
   UpdatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),

   UNIQUE (MovieID ASC)
);
GO

CREATE TABLE GP.Rating
(
	RatingID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	IMDBscore INT NOT NULL,
	VotesCount INT NOT NULL,
	MovieID INT NOT NULL FOREIGN KEY
		REFERENCES GP.Movies(MovieID),
	CreateddOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
	UpdatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET())

	UNIQUE (RatingID ASC)
);
GO

CREATE TABLE GP.Director
(
	MovieID INT NOT NULL FOREIGN KEY
		REFERENCES GP.Movies(MovieID),
	DirectorID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,		
	FirstName NVARCHAR(20) NOT NULL,
	LastName NVARCHAR(20) NOT NULL,
	CreateddOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
	UpdatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET())

	UNIQUE(DirectorID ASC)
);
GO

CREATE TABLE GP.Actor
(
	MovieID INT NOT NULL FOREIGN KEY
		REFERENCES GP.Movies(MovieID),
	ActorID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,		
	FirstName NVARCHAR(20) NOT NULL,
	LastName NVARCHAR(20) NOT NULL,
	CreateddOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
	UpdatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET())

	UNIQUE(ActorID ASC)
);
GO

CREATE TABLE GP.Genre
(
	MovieID INT NOT NULL FOREIGN KEY
		REFERENCES GP.Movies(MovieID),
	GenreID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	Genre NVARCHAR(15) NOT NULL,
	CreateddOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
	UpdatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET())

	UNIQUE(GenreID ASC)
);
GO

CREATE TABLE GP.Financial
(
	FinancialID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	MovieID INT NOT NULL FOREIGN KEY
		REFERENCES GP.Movies(MovieID),
	Budget INT NOT NULL,
	Gross INT NOT NULL,
	CreateddOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
	UpdatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET())

	UNIQUE(FinancialID ASC)
);
GO

CREATE TABLE GP.Region
(
	RegionID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	MovieID INT NOT NULL FOREIGN KEY
		REFERENCES GP.Movies(MovieID),
	Country NVARCHAR(25) NOT NULL,
	Language NVARCHAR(25) NOT NULL,
	CreateddOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
	UpdatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET())

	UNIQUE(RegionID ASC)
);
GO

CREATE TABLE GP.AdditionalInfo
(
	InfoID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	MovieID INT NOT NULL FOREIGN KEY
		REFERENCES GP.Movies(MovieID),
	MovieLink NVARCHAR(100) NOT NULL,
	AspectRatio NVARCHAR(10) NOT NULL,
	Color NVARCHAR (10) NOT NULL,
	CreateddOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
	UpdatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET())

	UNIQUE(InfoID ASC MovieLink ASC)
);
GO

