DROP TABLE IF EXISTS MOVIES 

GO
CREATE TABLE MOVIES
(
		Average_Vote INT NOT NULL,
		Title NVARCHAR(200) PRIMARY KEY NOT NULL,
		Popularity INT NOT NULL,
		Genre INT NOT NULL,
		Overview NVARCHAR(500) NOT NULL, 
		Release_Date DATE NOT NULL
)

GO
BULK INSERT MOVIES
FROM 'C:\Users\ansonj\Desktop\files.csv'
WITH
(
FIRSTROW = 2,
FIELDTERMINATOR = ',',
ROWTERMINATOR = '/n',
TABLOCK
)
